# -*- coding: utf-8 -*-
"""Movie-Recommender System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19y1MuIEG0i1NeVnm15tUnsTiXCaRg-lA
"""

import numpy as np
import pandas as pd

movies = pd.read_csv(r'D:\ML\projects\MovieRecdSys\tmdb_5000_movies.csv')
credits = pd.read_csv(r'D:\ML\projects\MovieRecdSys\tmdb_5000_credits.csv')

movies.head(1)

credits.head(1)

movies.shape

credits.shape

movies = movies.merge(credits, on='title')

movies.head(1)

movies.info()

movies.head()

movies = movies[['id', 'title', 'overview', 'genres', 'keywords','cast', 'crew']]

movies.info()

movies.head()

movies.isnull().sum()

movies.isnull().sum()

movies.dropna(inplace=True)

movies.duplicated().sum()

movies.drop_duplicates(inplace=True)

movies.duplicated().sum()

movies.iloc[0].genres

#{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction
# we have to extract the action adventure etc from the list

import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

def convert(obj):
  L = []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

movies['genres']= movies['genres'].apply(convert)

movies.head()

movies['keywords'] =   movies['keywords'].apply(convert)

movies.head()

def convert3(obj):
  L = []
  counter = 0
  for i in ast.literal_eval(obj):
    if counter !=3:
      L.append(i['name'])
    else:
      break
  return L

movies['cast'] = movies['cast'].apply(convert3)

movies.head()

def fetch_director(obj):
  L = []
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      L.append(i['name'])
      break
  return L

movies['crew'] =   movies['crew'].apply(fetch_director)

movies.head()

movies['overview'][0]

movies['overview'] =   movies['overview'].apply(lambda x : x.split())

movies.head()

movies['genres']= movies['genres'].apply(lambda x :[i.replace(" ","")for i in x])
movies['keywords']= movies['keywords'].apply(lambda x :[i.replace(" ","")for i in x])
movies['cast']= movies['cast'].apply(lambda x :[i.replace(" ","")for i in x])
movies['crew']= movies['crew'].apply(lambda x :[i.replace(" ","")for i in x])

movies.head()

movies['tags'] = movies['overview'] + movies['genres'] + movies['cast'] + movies['crew'] + movies['keywords']

movies.head()

new_df = movies[['id', 'title', 'tags']]

new_df.head()

new_df['tags'] = new_df['tags'].apply(lambda x : " ".join(x))

new_df.head(5)

new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

new_df.head()

import nltk
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

new_df['tags'] = new_df['tags'].apply(stem)

new_df.head()

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors

vectors[0]

cv.get_feature_names_out()
# for i in y:
#  print(i)

stem("loved")

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity[0]

similarity[0].shape

# sorting
#sorted(similarity[0], reverse=True)
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

recommend('Batman Begins')

new_df.iloc[1214].title

import pickle

pickle.dump(new_df, open('movies.pkl','wb'))

pickle.dump(similarity, open('similarity.pkl', 'wb'))